server:
  port: 8080
message: "Testing"
spring:
  profiles: default | dev
  application:
    name: books
  datasource:
    url: jdbc:mysql://localhost:3307/librarian
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  config:
    import: "configserver:http://localhost:8888"
  bus:
    enabled: true
  profile:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true