server:
  port: 8080
message: "Testing"
feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  bus:
    enabled: true
---
spring:
  profiles: default | dev
  datasource:
    url: jdbc:mysql://localhost:3306/librarian
    username: root
    password: Pass123!
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3307/librarian
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true