server:
  port: ${PORT:9715}
  tomcat:
    max-threads: 250
otp:
  validity: 300
  channels:
    default: MYBL OTP
feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 8000
        loggerLevel: basic
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles: default | development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apihub?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apihub?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: admin
    hikari:
      connection-timeout: 15000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 50 #maximum pool size which is currently 10
      idle-timeout: 15000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
feign:
  httpclient:
    maxConnections: 300
    maxConnectionsPerRoute: 150